export const GET_MEMES = "GET_MEMES";
export const GET_MEMES_LOADING = 'GET_MEMES_LOADING';
export const GET_MEMES_FAILED = "GET_MEMES_FAILED";



export const CAPTION_MEME = "CAPTION_MEME";
export const CAPTION_MEME_LOADING = 'CAPTION_MEME_LOADING';
export const CAPTION_MEME_FAILED = "CAPTION_MEME_FAILED";